Release/2.0
hms-networks/sc-flexy-tag-data-lib pull request #32
Opened 2020-12-08 21:21 UTC by oliver-walker-hms

2020-12-08 21:23 UTC, alexjhawk approved these changes, later dismissed

2020-12-08 21:35 UTC, TomKimsey requested changes

2020-12-08 21:35 UTC, TomKimsey commented on CHANGELOG.md
>  # Ewon Flexy Historical Data Queue Library Changelog
```suggestion
# Ewon Flexy Tag Data Library Changelog
```

2020-12-08 21:35 UTC, TomKimsey commented on README.md
>  ## [Description](#table-of-contents)
Line 1 also needs to be changed

2020-12-08 21:44 UTC, alexjhawk submitted a review, later dismissed

2020-12-08 21:45 UTC, alexjhawk approved these changes, later dismissed

2020-12-09 15:27 UTC, TomKimsey submitted a review, later dismissed

2020-12-09 15:43 UTC, oliver-walker-hms commented
rebased changes from other pr

2020-12-09 15:45 UTC, alexjhawk approved these changes

2020-12-09 16:50 UTC, TomKimsey approved these changes

2020-12-09 18:13 UTC, merged