Add support for Integer to string tag enumerations
hms-networks/sc-flexy-tag-data-lib pull request #42
Opened 2021-07-07 17:29 UTC by oliver-walker-hms

2021-07-07 17:31 UTC, alexjhawk commented
You should add a commit to increment the package.html (and any other) version number(s), then a RELEASE commit with updated changelog. Similar to https://github.com/hms-networks/sc-flexy-datapoint-lib/pull/16/commits

2021-07-08 12:48 UTC, alexjhawk requested changes

2021-07-08 12:48 UTC, alexjhawk commented on src/com/hms_networks/americas/sc/historicaldata/HistoricalDataManager.java
> +   * @throws JSONException
need description/reason for exception

2021-07-08 12:48 UTC, alexjhawk commented on src/com/hms_networks/americas/sc/historicaldata/HistoricalDataManager.java
> +   * @throws JSONException
need description/reason for exception

2021-07-08 12:48 UTC, alexjhawk commented on CHANGELOG.md
> +# Ewon Flexy Tag Data Library Changelog
This commit name might be better as "Updated changelog for previous updates"

2021-07-08 13:18 UTC, alexjhawk approved these changes

2021-07-09 13:02 UTC, it-hms approved these changes

2021-07-09 13:03 UTC, merged